name: test

permissions:
  contents: read
  statuses: write
  pull-requests: read
 
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
      
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: go coverage
        run: |
          go test -mod=readonly -v -race -covermode=atomic -coverprofile=coverage.out ./...

      - name: go mod
        run: |
          go mod vendor && git diff --exit-code

      - name: Test goreleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist --skip-publish

      - uses: codecov/codecov-action@v2
        if: success()
        with:
          file: ./coverage.out
          flags: attache
          name: attache
